#pragma once
#define TEST_OFF_MODE				1
#define	UPDATE_CP_MODE_TURBY		1
#define UPDATE_PATTERN_MODE_TURBY	1
#define UPDATE_CP_STEP_LENGTH		98

#define TURBY_CHAMBER_UPDATE		1
#define TURBY_CHAMBER_INITIAL_TEMP	25